packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - hono@4.13.2
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
